# Generated by Django 3.1.2 on 2021-05-09 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message="you can't rate more than 5"), django.core.validators.MinValueValidator(limit_value=1, message="you can't rate less than 1")]),
        ),
    ]
