name: django-app

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: dj_diplom
          POSTGRES_USER: owner_dj_diplom
          POSTGRES_PASSWORD: owner_dj_diplom
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        env:
          TESTING: 1
        run: pytest

  deploy:
    needs: tests

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: dj_diplom
          POSTGRES_USER: owner_dj_diplom
          POSTGRES_PASSWORD: owner_dj_diplom
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ci-cd-django-shop"
          heroku_email: dilovardehkanov730@gmail.com
          usedocker: True
